<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2.Time Series Graphics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Chapter_2_TS_Graphics_files/libs/clipboard/clipboard.min.js"></script>
<script src="Chapter_2_TS_Graphics_files/libs/quarto-html/quarto.js"></script>
<script src="Chapter_2_TS_Graphics_files/libs/quarto-html/popper.min.js"></script>
<script src="Chapter_2_TS_Graphics_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Chapter_2_TS_Graphics_files/libs/quarto-html/anchor.min.js"></script>
<link href="Chapter_2_TS_Graphics_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Chapter_2_TS_Graphics_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Chapter_2_TS_Graphics_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Chapter_2_TS_Graphics_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Chapter_2_TS_Graphics_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2.Time Series Graphics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="chapter-2-time-series-graphics-18th-march-2025" class="level2">
<h2 class="anchored" data-anchor-id="chapter-2-time-series-graphics-18th-march-2025">Chapter 2 Time-Series Graphics, 18th march 2025</h2>
<section id="load-libraries" class="level3">
<h3 class="anchored" data-anchor-id="load-libraries">Load libraries</h3>
</section>
<section id="chapter-2.2" class="level3">
<h3 class="anchored" data-anchor-id="chapter-2.2">Chapter 2.2</h3>
<section id="ansett-airlines-data" class="level4">
<h4 class="anchored" data-anchor-id="ansett-airlines-data">Ansett airlines data</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>tbl_ts [7,407 × 4] (S3: tbl_ts/tbl_df/tbl/data.frame)
 $ Week      : week [1:7407] 1989 W28, 1989 W29, 1989 W30, 1989 W31, 1989 W32, 1989 W...
 $ Airports  : chr [1:7407] "ADL-PER" "ADL-PER" "ADL-PER" "ADL-PER" ...
 $ Class     : chr [1:7407] "Business" "Business" "Business" "Business" ...
 $ Passengers: num [1:7407] 193 254 185 254 191 136 0 0 0 0 ...
 - attr(*, "key")= tibble [30 × 3] (S3: tbl_df/tbl/data.frame)
  ..$ Airports: chr [1:30] "ADL-PER" "ADL-PER" "ADL-PER" "MEL-ADL" ...
  ..$ Class   : chr [1:30] "Business" "Economy" "First" "Business" ...
  ..$ .rows   : list&lt;int&gt; [1:30] 
  .. ..$ : int [1:176] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ : int [1:283] 177 178 179 180 181 182 183 184 185 186 ...
  .. ..$ : int [1:283] 460 461 462 463 464 465 466 467 468 469 ...
  .. ..$ : int [1:176] 743 744 745 746 747 748 749 750 751 752 ...
  .. ..$ : int [1:283] 919 920 921 922 923 924 925 926 927 928 ...
  .. ..$ : int [1:283] 1202 1203 1204 1205 1206 1207 1208 1209 1210 1211 ...
  .. ..$ : int [1:176] 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 ...
  .. ..$ : int [1:282] 1661 1662 1663 1664 1665 1666 1667 1668 1669 1670 ...
  .. ..$ : int [1:282] 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 ...
  .. ..$ : int [1:175] 2225 2226 2227 2228 2229 2230 2231 2232 2233 2234 ...
  .. ..$ : int [1:282] 2400 2401 2402 2403 2404 2405 2406 2407 2408 2409 ...
  .. ..$ : int [1:282] 2682 2683 2684 2685 2686 2687 2688 2689 2690 2691 ...
  .. ..$ : int [1:176] 2964 2965 2966 2967 2968 2969 2970 2971 2972 2973 ...
  .. ..$ : int [1:283] 3140 3141 3142 3143 3144 3145 3146 3147 3148 3149 ...
  .. ..$ : int [1:283] 3423 3424 3425 3426 3427 3428 3429 3430 3431 3432 ...
  .. ..$ : int [1:176] 3706 3707 3708 3709 3710 3711 3712 3713 3714 3715 ...
  .. ..$ : int [1:282] 3882 3883 3884 3885 3886 3887 3888 3889 3890 3891 ...
  .. ..$ : int [1:282] 4164 4165 4166 4167 4168 4169 4170 4171 4172 4173 ...
  .. ..$ : int [1:176] 4446 4447 4448 4449 4450 4451 4452 4453 4454 4455 ...
  .. ..$ : int [1:283] 4622 4623 4624 4625 4626 4627 4628 4629 4630 4631 ...
  .. ..$ : int [1:283] 4905 4906 4907 4908 4909 4910 4911 4912 4913 4914 ...
  .. ..$ : int [1:176] 5188 5189 5190 5191 5192 5193 5194 5195 5196 5197 ...
  .. ..$ : int [1:282] 5364 5365 5366 5367 5368 5369 5370 5371 5372 5373 ...
  .. ..$ : int [1:282] 5646 5647 5648 5649 5650 5651 5652 5653 5654 5655 ...
  .. ..$ : int [1:176] 5928 5929 5930 5931 5932 5933 5934 5935 5936 5937 ...
  .. ..$ : int [1:282] 6104 6105 6106 6107 6108 6109 6110 6111 6112 6113 ...
  .. ..$ : int [1:282] 6386 6387 6388 6389 6390 6391 6392 6393 6394 6395 ...
  .. ..$ : int [1:175] 6668 6669 6670 6671 6672 6673 6674 6675 6676 6677 ...
  .. ..$ : int [1:283] 6843 6844 6845 6846 6847 6848 6849 6850 6851 6852 ...
  .. ..$ : int [1:282] 7126 7127 7128 7129 7130 7131 7132 7133 7134 7135 ...
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE
 - attr(*, "index")= chr "Week"
  ..- attr(*, "ordered")= logi TRUE
 - attr(*, "index2")= chr "Week"
 - attr(*, "interval")= interval [1:1] 1W
  ..@ .regular: logi TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 7,407 x 4 [1W]
# Key:       Airports, Class [30]
       Week Airports Class    Passengers
     &lt;week&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt;
 1 1989 W28 ADL-PER  Business        193
 2 1989 W29 ADL-PER  Business        254
 3 1989 W30 ADL-PER  Business        185
 4 1989 W31 ADL-PER  Business        254
 5 1989 W32 ADL-PER  Business        191
 6 1989 W33 ADL-PER  Business        136
 7 1989 W34 ADL-PER  Business          0
 8 1989 W35 ADL-PER  Business          0
 9 1989 W36 ADL-PER  Business          0
10 1989 W37 ADL-PER  Business          0
# ℹ 7,397 more rows</code></pre>
</div>
</div>
<p>Dataset containing 7407 rows and 4 coumns, with an index that captures weekly data. The unique key is captured by the unique combination of “Airports-Class” and the dataset contains 30 such unique keys or time-series.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Seasonality within the year is captured across years</p></li>
<li><p>Two unsual dips in the ts: 1) 1989, whyen passenger count was zero; 2) 1992, passenger count at 15K</p></li>
<li><p>Data tends to trend upwards in th 1991-92 period</p></li>
<li><p>Perhaps, there is a downward trend from 1988-90?</p></li>
</ul>
</section>
</section>
<section id="chapter-2.3" class="level3">
<h3 class="anchored" data-anchor-id="chapter-2.3">Chapter 2.3</h3>
<section id="trend" class="level4">
<h4 class="anchored" data-anchor-id="trend">Trend:</h4>
<ul>
<li>Long-term direction of the time-series. It may slope upwards or downwards. The trend is the ts can change over-time. It does not need to be uni-directional. This is called “changing direction” in the ts.</li>
</ul>
</section>
<section id="seasonality" class="level4">
<h4 class="anchored" data-anchor-id="seasonality">Seasonality:</h4>
<ul>
<li>Repetetive patterns in the ts at a known frequency is called “seasonality”. Example - day-of-week affect on traffic volume, monthly-sales patterns for commodities such as umbrellas.</li>
</ul>
</section>
<section id="cycle" class="level4">
<h4 class="anchored" data-anchor-id="cycle">Cycle:</h4>
<ul>
<li>Repetetive patterns in data but not at known frequency is called “cycle”. Example - The Chemical industry goes through cycles of boom and bust. This is inevitable, the only thing that changes and is perhasp not predictable is the gap between these cycles. The duration of these repeated pattern is atleast 2-years.</li>
</ul>
</section>
<section id="cycle-vs-seasonality" class="level4">
<h4 class="anchored" data-anchor-id="cycle-vs-seasonality">Cycle vs Seasonality?</h4>
<ul>
<li><p>Seasonality is related to the calendar features ie the patterns tends to repat every year</p>
<ul>
<li>Cycles occur at a frequency greater than 2-years</li>
</ul></li>
<li><p>magnitude of cycles tends to be greater than that of seasonal pattern</p></li>
</ul>
</section>
</section>
<section id="chapter-2.4" class="level3">
<h3 class="anchored" data-anchor-id="chapter-2.4">Chapter 2.4</h3>
<section id="seasonal-plot" class="level4">
<h4 class="anchored" data-anchor-id="seasonal-plot">Seasonal plot</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 52,608 x 5 [30m] &lt;Australia/Melbourne&gt;
   Time                Demand Temperature Date       Holiday
   &lt;dttm&gt;               &lt;dbl&gt;       &lt;dbl&gt; &lt;date&gt;     &lt;lgl&gt;  
 1 2012-01-01 00:00:00  4383.        21.4 2012-01-01 TRUE   
 2 2012-01-01 00:30:00  4263.        21.0 2012-01-01 TRUE   
 3 2012-01-01 01:00:00  4049.        20.7 2012-01-01 TRUE   
 4 2012-01-01 01:30:00  3878.        20.6 2012-01-01 TRUE   
 5 2012-01-01 02:00:00  4036.        20.4 2012-01-01 TRUE   
 6 2012-01-01 02:30:00  3866.        20.2 2012-01-01 TRUE   
 7 2012-01-01 03:00:00  3694.        20.1 2012-01-01 TRUE   
 8 2012-01-01 03:30:00  3562.        19.6 2012-01-01 TRUE   
 9 2012-01-01 04:00:00  3433.        19.1 2012-01-01 TRUE   
10 2012-01-01 04:30:00  3359.        19.0 2012-01-01 TRUE   
# ℹ 52,598 more rows</code></pre>
</div>
</div>
<ul>
<li><p>Victoria electricity consumption data.</p></li>
<li><p>52608 rows and 5 columns. Indexed every 30 minutes.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observation:</p>
<ul>
<li>Seasonal pattern recorded at a hour-of-day frequency</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Seasonality at day-of-week (and hour-of-day) frequency</p></li>
<li><p>The data repeats the hour-of-day pattern for all weekdays</p></li>
<li><p>The electricity-consumption tends to be the same theough the week ad dips slighly for Saturday &amp; Sunday!</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observation</p>
<ul>
<li><p>Zooming out to look at the pattern on a yearly-basis.</p></li>
<li><p>The fact that the data-patterns overlap across years suggests that there is not much of a trend to pick-up!</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observation:</p>
<ul>
<li>Yes, it’s true, that there is not much of a trend in this dataset!</li>
</ul>
</section>
</section>
<section id="chapter-2.5-seasonality" class="level3">
<h3 class="anchored" data-anchor-id="chapter-2.5-seasonality">Chapter 2.5: Seasonality</h3>
<section id="turning-data-into-a-tsibble" class="level4">
<h4 class="anchored" data-anchor-id="turning-data-into-a-tsibble">Turning data into a tsibble</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 204 x 2 [1M]
       index  Cost
       &lt;mth&gt; &lt;dbl&gt;
 1  1991 Jul  3.53
 2  1991 Aug  3.18
 3 1991 Sept  3.25
 4  1991 Oct  3.61
 5  1991 Nov  3.57
 6  1991 Dec  4.31
 7  1992 Jan  5.09
 8  1992 Feb  2.81
 9  1992 Mar  2.99
10  1992 Apr  3.20
# ℹ 194 more rows</code></pre>
</div>
</div>
<ul>
<li><p>The original ts data had monthly-data. since that was the only time dimension, that becomes the index.</p></li>
<li><p>Key is the other dimension in a tsibble. Key(/s) reflect the subjects for whom the time-series is recorded. In this ts there is no information provided for the key.</p></li>
<li><p>Cost is the measure that is recorded in the time-series. this reflects the values of the “measure” at monthly (index) time periods.</p></li>
</ul>
</section>
<section id="seasonal-sub-series-plot" class="level4">
<h4 class="anchored" data-anchor-id="seasonal-sub-series-plot">Seasonal sub-series plot</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>This is a faceted plot for each season in the data. Since the data was re[ported at a monthly frequency, seasons were the months.</p></li>
<li><p>The chart reveals not just the seasonal trend but also the change over time</p></li>
<li><p>Its clear from the above charts that Jan tends to be the month of highest cost. The blue-lines reflect the average over time.</p></li>
</ul>
</section>
<section id="aus-holiday-tourism" class="level4">
<h4 class="anchored" data-anchor-id="aus-holiday-tourism">Aus holiday tourism</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 640 x 3 [1Q]
# Key:       State [8]
   State Quarter Trips
   &lt;chr&gt;   &lt;qtr&gt; &lt;dbl&gt;
 1 ACT   1998 Q1  196.
 2 ACT   1998 Q2  127.
 3 ACT   1998 Q3  111.
 4 ACT   1998 Q4  170.
 5 ACT   1999 Q1  108.
 6 ACT   1999 Q2  125.
 7 ACT   1999 Q3  178.
 8 ACT   1999 Q4  218.
 9 ACT   2000 Q1  158.
10 ACT   2000 Q2  155.
# ℹ 630 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>“autoplot” gives all the series in the data. In our case we had 8 keys (States) recording tourist volume at a quarterly period (index)</p></li>
<li><p>NSW has the highest volume; Victoria has biggeest variance; Western-Australia has a jump in its trend in 2015!</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>In general, tourist volume seems to be up across all states in 2015</p></li>
<li><p>Th blue line depicts the quaretrly-seasonality across states.</p>
<ul>
<li><p>Q1 is most popular for Victoria, Tasmania, NSW. South Australia</p></li>
<li><p>Q3 is most popular in Northern Territories and Queensland</p></li>
<li><p>Western Australia and ACT have no seasonal variation!</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="chapter-2.7-lags" class="level3">
<h3 class="anchored" data-anchor-id="chapter-2.7-lags">Chapter 2.7: Lags</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Dots indicate the quarter on the vertical axis.</p></li>
<li><p>We are plotting yt vs yt-k, k=1..9</p></li>
<li><p>So for the lag-1 facet, we have yellow on the extreme left suggesting that’s a Q4 value vs a Q3 value on the x-axis</p></li>
<li><p>We also notice that lag-4 and lag-8 line up against a line. This suggests the seasonal nature of the data. Clear indication of quarterly seasonality.</p></li>
</ul>
</section>
<section id="chapter-2.8-autocorelation" class="level3">
<h3 class="anchored" data-anchor-id="chapter-2.8-autocorelation">Chapter 2.8: Autocorelation</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 9 x 2 [1Q]
       lag      acf
  &lt;cf_lag&gt;    &lt;dbl&gt;
1       1Q -0.0530 
2       2Q -0.758  
3       3Q -0.0262 
4       4Q  0.802  
5       5Q -0.0775 
6       6Q -0.657  
7       7Q  0.00119
8       8Q  0.707  
9       9Q -0.0888 </code></pre>
</div>
</div>
<p>Theory:</p>
<ul>
<li><p>autocorelation: correlation between value of the series that are apart by k periods.</p></li>
<li><p>r1 = correation between value that are distanced by k=1 time period</p></li>
<li><p>In general rk = numerator/denomintaor</p>
<ul>
<li><p>numerator = sum of product terms such that product is of the form (y_t - y_bar)(y_t-k -y_bar)</p>
<ul>
<li><p>the terms summed over the entire time-series T</p></li>
<li><p>the starting point for the summation is t=k</p></li>
<li><p>so if the time-series has 10 terms ie T=10</p></li>
<li><p>we will sum the product of the form in the first bullet for all ks from 2..10</p></li>
<li><p>so the numerator will have (10-2)+1= product terms that will be summed</p></li>
</ul></li>
<li><p>denominator = variance of the time series ie sum t=1..T, terms of the form (y_t - y_bar)^2</p></li>
</ul></li>
</ul>
<section id="correlogram" class="level4">
<h4 class="anchored" data-anchor-id="correlogram">Correlogram</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>autocorrelations are high and positive when lags are multiples of 4 quarters.</p>
<ul>
<li>This suggests that there is strong seasonal pattern on a quarterly</li>
</ul></li>
<li><p>autocorelation is high and negative for lags that are at periods 2,6,10,14…</p>
<ul>
<li>This suggests that values are at trough and peaks at these intervals</li>
</ul></li>
<li><p>The blue line gives the significnat level for correlations</p></li>
</ul>
</section>
<section id="trend-seasonality" class="level4">
<h4 class="anchored" data-anchor-id="trend-seasonality">Trend &amp; Seasonality</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Since the lag-1 correlation is high, the data has strong trend.</p></li>
<li><p>We also notice the highest spike at a 12, 24, 26..time interval which suggests stronong correlation with yearly values which is essentially the trend!</p></li>
<li><p>When the data has only seasonality, the lag-1 will not be this strong.</p>
<ul>
<li>the lag at the seasonal period will have the strongest correlation.</li>
</ul></li>
<li><p>For data that has both trend and seasoanlity, we will likely get charts like th one above.</p></li>
</ul>
</section>
<section id="white-noise" class="level4">
<h4 class="anchored" data-anchor-id="white-noise">White-noise</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li>The significant bands are at +/- 1.96/sqrt(T) distance from the mean. Thsi gives the 95% confidence-interval for the distribution.</li>
</ul>
</section>
</section>
<section id="exercises" class="level3">
<h3 class="anchored" data-anchor-id="exercises">Exercises:</h3>
<section id="bricks" class="level4">
<h4 class="anchored" data-anchor-id="bricks">1.?Bricks</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 218 x 7 [1Q]
   Quarter  Beer Tobacco Bricks Cement Electricity   Gas
     &lt;qtr&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;
 1 1956 Q1   284    5225    189    465        3923     5
 2 1956 Q2   213    5178    204    532        4436     6
 3 1956 Q3   227    5297    208    561        4806     7
 4 1956 Q4   308    5681    197    570        4418     6
 5 1957 Q1   262    5577    187    529        4339     5
 6 1957 Q2   228    5651    214    604        4811     7
 7 1957 Q3   236    5317    227    603        5259     7
 8 1957 Q4   320    6152    222    582        4735     6
 9 1958 Q1   272    5758    199    554        4608     5
10 1958 Q2   233    5641    229    620        5196     7
# ℹ 208 more rows</code></pre>
</div>
</div>
<ul>
<li><p>Time interval for the series is quarterly</p></li>
<li><p>autoplot for the Bricks series</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Adding labels for the axis and a title</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gafa-stock" class="level4">
<h4 class="anchored" data-anchor-id="gafa-stock">2. Gafa-stock:</h4>
<p>Find the days that correspond to the highest price for each of the stocks in the dataset</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 5,032 x 8 [!]
# Key:       Symbol [4]
   Symbol Date        Open  High   Low Close Adj_Close    Volume
   &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 AAPL   2014-01-02  79.4  79.6  78.9  79.0      67.0  58671200
 2 AAPL   2014-01-03  79.0  79.1  77.2  77.3      65.5  98116900
 3 AAPL   2014-01-06  76.8  78.1  76.2  77.7      65.9 103152700
 4 AAPL   2014-01-07  77.8  78.0  76.8  77.1      65.4  79302300
 5 AAPL   2014-01-08  77.0  77.9  77.0  77.6      65.8  64632400
 6 AAPL   2014-01-09  78.1  78.1  76.5  76.6      65.0  69787200
 7 AAPL   2014-01-10  77.1  77.3  75.9  76.1      64.5  76244000
 8 AAPL   2014-01-13  75.7  77.5  75.7  76.5      64.9  94623200
 9 AAPL   2014-01-14  76.9  78.1  76.8  78.1      66.1  83140400
10 AAPL   2014-01-15  79.1  80.0  78.8  79.6      67.5  97909700
# ℹ 5,022 more rows</code></pre>
</div>
</div>
<p>Peak closing price for each stock symbol:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 4 x 8 [!]
# Key:       Symbol [4]
# Groups:    Symbol [4]
  Symbol Date        Open  High   Low Close Adj_Close   Volume
  &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 AAPL   2018-10-03  230.  233.  230.  232.      230. 28654800
2 AMZN   2018-09-04 2026. 2050. 2013  2040.     2040.  5721100
3 FB     2018-07-25  216.  219.  214.  218.      218. 58954200
4 GOOG   2018-07-26 1251  1270. 1249. 1268.     1268.  2405600</code></pre>
</div>
</div>
<p><img src="images/clipboard-9133593.png" class="img-fluid"></p>
</section>
<section id="aus_arrivals-data-run-autoplot-gg_subseries-gg_season" class="level4">
<h4 class="anchored" data-anchor-id="aus_arrivals-data-run-autoplot-gg_subseries-gg_season">6. “aus_arrivals” data run autoplot(), gg_subseries(), gg_season()</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 508 x 3 [1Q]
# Key:       Origin [4]
   Quarter Origin Arrivals
     &lt;qtr&gt; &lt;chr&gt;     &lt;int&gt;
 1 1981 Q1 Japan     14763
 2 1981 Q2 Japan      9321
 3 1981 Q3 Japan     10166
 4 1981 Q4 Japan     19509
 5 1982 Q1 Japan     17117
 6 1982 Q2 Japan     10617
 7 1982 Q3 Japan     11737
 8 1982 Q4 Japan     20961
 9 1983 Q1 Japan     20671
10 1983 Q2 Japan     12235
# ℹ 498 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observation:</p>
<ul>
<li>The Japanese tourists seem to be trending dwonwards from 1996 onwards</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observation:</p>
<ul>
<li><p>The plot suggest the clear shift in trend across years. For All countries except Japan, the recent years have higher values</p></li>
<li><p>The chart also clearly gives us the seasonal pattern and how this has changed over time. Example for the UK tourists the season pattern for highs in Q1 and Q4 ar more pronounced than they were back in the 1980s</p></li>
</ul>
</section>
<section id="aus_livestock" class="level4">
<h4 class="anchored" data-anchor-id="aus_livestock">10. aus_livestock</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 29,364 x 4 [1M]
# Key:       Animal, State [54]
       Month Animal                     State                        Count
       &lt;mth&gt; &lt;fct&gt;                      &lt;fct&gt;                        &lt;dbl&gt;
 1  1976 Jul Bulls, bullocks and steers Australian Capital Territory  2300
 2  1976 Aug Bulls, bullocks and steers Australian Capital Territory  2100
 3 1976 Sept Bulls, bullocks and steers Australian Capital Territory  2100
 4  1976 Oct Bulls, bullocks and steers Australian Capital Territory  1900
 5  1976 Nov Bulls, bullocks and steers Australian Capital Territory  2100
 6  1976 Dec Bulls, bullocks and steers Australian Capital Territory  1800
 7  1977 Jan Bulls, bullocks and steers Australian Capital Territory  1800
 8  1977 Feb Bulls, bullocks and steers Australian Capital Territory  1900
 9  1977 Mar Bulls, bullocks and steers Australian Capital Territory  2700
10  1977 Apr Bulls, bullocks and steers Australian Capital Territory  2300
# ℹ 29,354 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  Animal                         n
  &lt;fct&gt;                      &lt;int&gt;
1 Calves                      4464
2 Cattle (excl. calves)       4464
3 Pigs                        4464
4 Sheep                       4464
5 Bulls, bullocks and steers  4056
6 Lambs                       3906
7 Cows and heifers            3546</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
  State                            n
  &lt;fct&gt;                        &lt;int&gt;
1 New South Wales               3810
2 Queensland                    3810
3 South Australia               3810
4 Tasmania                      3810
5 Victoria                      3810
6 Western Australia             3810
7 Australian Capital Territory  3300
8 Northern Territory            3204</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>The data appears to have cycles. Between Jan 1990 and Jan 2010, for the twenty-year period we see a trend that grows for 10 years and then falls for the next 10 years.</p></li>
<li><p>Though the pattern did not quite repeat fro the period 1980-1990, in which case the upward and dwonward trend persist for 5 years each!</p></li>
<li><p>Does the data have any seasonal pattern?</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Seasonality is not strong!</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>High auto-correlation but not much seasonality!</p></li>
<li><p>The correlation jumps at period = 12, 24…</p></li>
<li><p>We see the cylical pattern but the periodicity is not consistent.</p>
<ul>
<li><p>The correlation reverses at the 60 month-mark, which suggests that the trend is shifting.</p></li>
<li><p>It continues to persis in the negatie direction until 114, which suggest that as time-periods inc the volume of pigs being slaughtered goes down.</p></li>
<li><p>From 114 onwards the correlation changes dirction and starts to become less negative, although until the period 219 it is outside the significance line. This suggests that the autocrelation is strong albet it less negative. Thsi means as t increases the volume tends to go down.</p></li>
</ul></li>
</ul>
</section>
<section id="google" class="level4">
<h4 class="anchored" data-anchor-id="google">11. Google</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 251 x 8 [!]
# Key:       Symbol [1]
   Symbol Date        Open  High   Low Close Adj_Close  Volume
   &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 GOOG   2018-01-02 1048. 1067. 1045. 1065      1065  1237600
 2 GOOG   2018-01-03 1064. 1086. 1063. 1082.     1082. 1430200
 3 GOOG   2018-01-04 1088  1094. 1084. 1086.     1086. 1004600
 4 GOOG   2018-01-05 1094  1104. 1092  1102.     1102. 1279100
 5 GOOG   2018-01-08 1102. 1111. 1102. 1107.     1107. 1047600
 6 GOOG   2018-01-09 1109. 1111. 1101. 1106.     1106.  902500
 7 GOOG   2018-01-10 1097. 1105. 1096. 1103.     1103. 1042800
 8 GOOG   2018-01-11 1106. 1107. 1100. 1106.     1106.  978300
 9 GOOG   2018-01-12 1102. 1124. 1101. 1122.     1122. 1720500
10 GOOG   2018-01-16 1133. 1140. 1118. 1122.     1122. 1575300
# ℹ 241 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tsibble: 251 x 10 [1]
# Key:       Symbol [1]
   Symbol Date        Open  High   Low Close Adj_Close Volume trading_day   diff
   &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;       &lt;int&gt;  &lt;dbl&gt;
 1 GOOG   2018-01-02 1048. 1067. 1045. 1065      1065  1.24e6           1 NA    
 2 GOOG   2018-01-03 1064. 1086. 1063. 1082.     1082. 1.43e6           2 17.5  
 3 GOOG   2018-01-04 1088  1094. 1084. 1086.     1086. 1.00e6           3  3.92 
 4 GOOG   2018-01-05 1094  1104. 1092  1102.     1102. 1.28e6           4 15.8  
 5 GOOG   2018-01-08 1102. 1111. 1102. 1107.     1107. 1.05e6           5  4.71 
 6 GOOG   2018-01-09 1109. 1111. 1101. 1106.     1106. 9.02e5           6 -0.680
 7 GOOG   2018-01-10 1097. 1105. 1096. 1103.     1103. 1.04e6           7 -3.65 
 8 GOOG   2018-01-11 1106. 1107. 1100. 1106.     1106. 9.78e5           8  2.91 
 9 GOOG   2018-01-12 1102. 1124. 1101. 1122.     1122. 1.72e6           9 16.7  
10 GOOG   2018-01-16 1133. 1140. 1118. 1122.     1122. 1.58e6          10 -0.5  
# ℹ 241 more rows</code></pre>
</div>
</div>
<p>Plot the difference:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>ACF on diffL:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Differencing has turned the data into a white noise.</p>
<p>Was the close data any different?</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Is this diferent from the original?</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>No difference between the original and the data with difference!</p>
<p>OK so let’s check for auto-correlation in the Google data</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_2_TS_Graphics_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Interesting!</p>
<p>The original data had a clear autocorelation structure, but when we difference the time-seriees by taking one-day lag on closing data, the time-series becomes white-noise!</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>